first = "Ivan"
last = "Marinov"
sum = 500
discount = 0.25
base = 2
exponent = 10
full = first + " " + last
sumd = sum - (sum * discount)
result1 = base ** exponent
result2 = full * result1
minsum = -sum
newsum = -minsum 